@startuml
autonumber
title       User wants to add a comment
actor       User
participant Application
database    Database

ref over User, Application, Database: Login
ref over User, Application, Database: Show articles
ref over User, Application, Database: Show article

User -> Application: POST /article/:slug
Application -> Application: Check values
alt values are valid
    Application -> Database: Add comment
    Database -> Application: Add comment
    Application -> User: Redirect to /article/:slug
else values are invalid
    Application -> Application: Add error
    Application -> User: Render /article/:slug
end

@enduml
