@startuml
autonumber
title       "Admin" wants to validate a user
actor       "Admin"
participant Application
database    Database

ref over Admin, Application, Database: Login

"Admin" -> Application: GET /admin
Application -> Database: Get inactive users
Database -> Database: Query inactive users
Database -> Application: Return inactive users
"Admin" <-- Application: Render /admin

"Admin" -> Application: GET /admin/activate-user/:id
Application -> Database: Activate user
Database -> Database: Query user
Database -> Application: Return user
"Admin" <-- Application: Redirect to /admin

@enduml
